[project]
name = "check-drone-builds"
version = "1.0.0"
description = "Icinga2 check to monitor all builds are in the green"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "coverage>=7.9.1",
    "pytest>=8.3.5",
    "ruff>=0.11.11",
]
