name: lint-test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Lint
        run: uv run ruff check

      - name: Run unit-tests
        run: uv run pytest --cov=check_drone_builds